# Generated by Django 3.2.16 on 2022-11-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='account',
            field=models.IntegerField(blank=True, default=1, verbose_name='City Account'),
        ),
    ]
